name: Deploy

#will dispatch the deploy when active manually (workflow_dispatch) or by push on the branches bellow
on:
  workflow_dispatch:
  push:
    branches: ["*"]
  
jobs:
  deploy-front:
    runs-on: ubuntu-latest
    concurrency: deploy-to-front
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker-compose build
      - run: docker-compose up -d 